[DNM] updated references of base plugins to netcommon
ansible-collections/cisco.nxos pull request #419
Opened 2022-02-03 10:24 UTC by KB-perByte

##### SUMMARY

Minimum required ansible.netcommon version is 2.5.0
Updated base plugin references to ansible.netcommon

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-04-21 10:17 UTC, NilashishC commented
recheck

2022-04-21 13:39 UTC, Qalthos requested changes

2022-04-21 13:39 UTC, Qalthos commented on galaxy.yml
> +  "ansible.netcommon": ">=2.5.0"
This has to be 2.5.1 to work
```suggestion
  "ansible.netcommon": ">=2.5.1"
```

2022-04-21 13:41 UTC, Qalthos commented on changelogs/fragments/netcommon_ref_update.yaml
> +  - "Minimum required ansible.netcommon version is 2.5.0."
```suggestion
  - "Minimum required ansible.netcommon version is 2.5.1."
```

2022-04-25 08:47 UTC, NilashishC commented
recheck

2022-04-25 13:19 UTC, Qalthos approved these changes

2022-04-25 16:23 UTC, NilashishC commented
recheck

2022-04-26 05:22 UTC, NilashishC commented
recheck

2022-04-26 05:22 UTC, NilashishC approved these changes

2022-04-26 09:38 UTC, NilashishC commented
recheck

2022-04-26 18:47 UTC, merged