Fix issues reported by ansible-lint
ansible-collections/cisco.nxos pull request #518
Opened 2022-05-26 19:51 UTC by cidrblock

##### SUMMARY
Fix all errror reported by ansible-lint

##### ISSUE TYPE
Test cleanup

##### COMPONENT NAME
integration tests

##### ADDITIONAL INFORMATION
A future PR might be put forth to enable ansible-lint as a github action: https://github.com/ansible-community/ansible-lint-action

2022-05-30 04:21 UTC, NilashishC approved these changes

2022-05-30 04:41 UTC, NilashishC requested changes

2022-05-30 04:41 UTC, NilashishC commented on tests/integration/targets/nxos_acls/tests/common/parsed.yml
> +        running_config: >-
```
 ok: [nxos] => {
2022-05-26 20:22:14.991401 | controller |     "changed": false,
2022-05-26 20:22:14.991404 | controller |     "invocation": {
2022-05-26 20:22:14.991407 | controller |         "module_args": {
2022-05-26 20:22:14.991410 | controller |             "config": null,
2022-05-26 20:22:14.991414 | controller |             "running_config": "ip access-list ACL1v4 10 permit ip any any 20 deny udp any any ip access-list ACL2v4 10 permit ahp 192.0.2.0 0.0.0.255 any ipv6 access-list ACL1v6 10 permit sctp any any 20 remark IPv6 ACL ipv6 access-list ACL2v6 10 deny ipv6 any 2001:db8:3000::36/128 20 permit tcp 2001:db8:2000:2::2/128 2001:db8:2000:ab::2/128",
2022-05-26 20:22:14.991448 | controller |             "state": "parsed"
2022-05-26 20:22:14.991451 | controller |         }
2022-05-26 20:22:14.991454 | controller |     },
2022-05-26 20:22:14.991457 | controller |     "parsed": [
2022-05-26 20:22:14.991459 | controller |         {
2022-05-26 20:22:14.991462 | controller |             "acls": [
2022-05-26 20:22:14.991465 | controller |                 {
2022-05-26 20:22:14.991469 | controller |                     "name": "ACL1v4 10 permit ip any any 20 deny udp any any ip access-list ACL2v4 10 permit ahp 192.0.2.0 0.0.0.255 any ipv6 access-list ACL1v6 10 permit sctp any any 20 remark IPv6 ACL ipv6 access-list ACL2v6 10 deny ipv6 any 2001:db8:3000::36/128 20 permit tcp 2001:db8:2000:2::2/128 2001:db8:2000:ab::2/128"
2022-05-26 20:22:14.991474 | controller |                 }
2022-05-26 20:22:14.991477 | controller |             ],
2022-05-26 20:22:14.991480 | controller |             "afi": "ipv4"
2022-05-26 20:22:14.991483 | controller |         }
2022-05-26 20:22:14.991486 | controller |     ]
2022-05-26 20:22:14.991489 | controller | }
2022-05-26 20:22:14.991492 | controller |
```

2022-05-30 04:41 UTC, NilashishC commented on tests/integration/targets/nxos_acls/tests/common/parsed.yml
> +        running_config: >-
This somehow breaks the parsed test.

2022-05-31 11:30 UTC, NilashishC requested changes

2022-05-31 13:44 UTC, ssbarnea approved these changes

2022-06-01 07:28 UTC, NilashishC approved these changes

2022-06-01 07:28 UTC, merged