fixed typo in docs
ansible-collections/cisco.nxos pull request #545
Opened 2022-08-05 12:24 UTC by insobi

##### SUMMARY

Fixed typo in Examples

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-08-11 04:44 UTC, NilashishC commented
@insobi Thank you for this PR. But there's a couple of things going on here. If you look at the `Files changed` tab, you'd see no changes being made by this patch. This is because even though you updated the RST, you did not make any changes to the module documentation in the Python file. We run pre-commit hook in this repo, which triggers the `collection_prep` tool, that is responsible for keeping module documentation and the RST docs in sync. Since you didn't change the module documentation, this tool reverted the RST change to it's previous state. In order to get this working, please push the corresponding changes to the module documentation as well. Thank you!

2022-08-11 04:44 UTC, NilashishC requested changes
@insobi Thank you for this PR. But there's a couple of things going on here. If you look at the Files changed tab, you'd see no changes being made by this patch. This is because even though you updated the RST, you did not make any changes to the module documentation in the Python file. We run pre-commit hook in this repo, which triggers the collection_prep tool, that is responsible for keeping module documentation and the RST docs in sync. Since you didn't change the module documentation, this tool reverted the RST change to it's previous state. In order to get this working, please push the corresponding changes to the module documentation as well. Thank you!

2022-08-22 03:55 UTC, insobi commented
@NilashishC Thank you for your feedback. I added modified files.

2022-08-25 14:09 UTC, NilashishC approved these changes

2022-09-06 19:52 UTC, Qalthos approved these changes

2022-09-07 04:36 UTC, merged