[snmp_server] fix user negation when authentication options are present
ansible-collections/cisco.nxos pull request #657
Opened 2023-04-01 05:23 UTC by KB-perByte

##### SUMMARY

Fixes #439

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

nxos_snmp_server

##### ADDITIONAL INFORMATION

https://github.com/ansible-collections/cisco.nxos/issues/439
```paste below
switch(config)# do show running-config | section '^snmp-server'
snmp-server user snmp-user1 network-admin auth sha 20***042 priv aes-128 374***037 localizedV2key
switch(config)# no snmp-server user snmp-user1 network-admin auth sha 205B***3042 priv aes-128 374***037 localizedV2key
Cannot delete the last group of the user!  <<<<<<<<<<<<<<<<<<< issue
switch(config)# no snmp-server user snmp-user1 ?
  <CR>         
  WORD         Group name (ignored for notif target user) (Max Size 28)
  auth         Authentication parameters for the user
  enforcePriv  Enforce privacy for the user
  use-ipv4acl  Specify IPv4 ACL, the ACL name specified after must be IPv4 ACL.
  use-ipv6acl  Specify IPv6 ACL, the ACL name specified after must be IPv6 ACL.
switch(config)# no snmp-server user snmp-user1 network-admin
Cannot delete the last group of the user! <<<<<<<<<<<<<<<<<<<<<< Issue
switch(config)# no snmp-server user snmp-user1 <<<<<<<<<<<<<<< Works 
switch(config)#
```

2023-04-01 05:28 UTC, KB-perByte commented on changelogs/fragments/snmp_server_fix.yml
> +  - "`snmp_server` - fix host delete when authentication options are enables."
```suggestion
  - "`snmp_server` - fix host delete when authentication options are present."
```

2023-04-05 13:29 UTC, Qalthos requested changes

2023-04-05 13:29 UTC, Qalthos commented on changelogs/fragments/snmp_server_fix.yml
> +  - "`snmp_server` - fix host delete when authentication options are present."
This gets turned into rst which does strange things with single backticks. But we don't usually use them for the plugin anyway.
```suggestion
  - "snmp_server - fix host delete when authentication options are present."
```

2023-09-14 06:36 UTC, NilashishC approved these changes

2023-09-14 06:37 UTC, merged